---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Add docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add docker repository
    apt_repository: 
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  
  - name: Install packages
    apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce'] 
        state: present 
        update_cache: yes
